ApiConfig:
  listen_interface: 0.0.0.0
  listen_port: 6544
  hostname: https://api.{{ caliopen_domain_name }}
  port: 443
  BackendConfig:
    backend_name: cassandra
    backend_settings:
      hosts:
{% for host in groups['store'] %}
      - {{ hostvars[host]['private_ips'][0] }}
{% endfor %}
      keyspace: {{ caliopen_cassandra_keyspace }}
      consistency_level: 1
      raw_size_limit: 1048576                                # max size in bytes for objects in db. Use S3 interface if larger.
      object_store: s3
      object_store_settings:
        endpoint: {{ object_store_host }}:9000
        access_key: {{ object_store_access_key }}
        secret_key: {{ object_store_secret_key }}
        location: eu-fr-paris
        buckets:
          raw_messages: {{ caliopen_bucket_raw_message }}                # bucket name to put raw messages to
          temporary_attachments: {{ caliopen_bucket_tmp_attachment }}    # bucket name to store draft attachments
      use_vault: true
      vault_settings:
        url: https://{{ vault_host }}:{{ vault_port }}
        username: {{ vault_api_username }}
        password: {{ vault_api_password }}
  IndexConfig:
    index_name: elasticsearch
    index_settings:
      hosts:
{% for host in groups['store'] %}
      - http://{{ hostvars[host]['private_ips'][0] }}:9200
{% endfor %}
  NatsConfig:
    url: nats://{{ nats_host }}:4222
    outSMTP_topic: outboundSMTP     # topic's name to post "send" draft order
    outIMAP_topic: outboundIMAP     # topic's name for "send" draft order via remote SMTP+IMAP
    outTWITTER_topic: twitter_dm    # topics's name for "send" draft order via TWITTER
    contacts_topic: contactAction   # topic's name to post messages regarding contacts' events
    keys_topic: keyAction             # topic's name to post messages regarding public key events
    users_topic: userAction           # topic's name to post messages regarding users events
    idpoller_topic: idCache           # topic's name to post messages to idpoller regarding identities management

  swaggerSpec: /etc/caliopen/swagger.json #absolute path or relative path to go.server bin
  RedisConfig:
    host: {{ redis_host }}:6379
    password: ""      #no password set
    db: 0             #use default db
  NotifierConfig:
    base_url: https://{{ caliopen_domain_name }}
    admin_username: admin
    templates_path: "/etc/caliopen/notifiers/templates/"
  Providers:                                                # temporary supported providers list for remote identities before moving this data into store facility
  - name: gmail
    protocol: email
    infos:
      client_id: {{ gmail_oauth_app_key }}
      client_secret: {{ gmail_oauth_app_secret }}
      imapserver: imap.gmail.com:993
      smtpserver: smtp.gmail.com:587
  - name: twitter
    protocol: twitter
    infos:
      consumer_key: {{ twitter_oauth_app_key }}
      consumer_secret: {{ twitter_oauth_app_secret }}

ProxyConfig:
  listen_interface: 0.0.0.0
  port: 31415
  routes:
  - /api/v2/: 127.0.0.1:6544
  - /: apiv1:6543         # route "/" catch all other requests
